spring:
  application:
    name: kafka-practice

  kafka:
    bootstrap-servers:
      - localhost:9092
    client-id: noose

    producer:
      acks: -1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      properties:
        max.in.flight.per.connection: 5
        retries: 3
        enable.idempotence: true
