### 메시지 전송
POST localhost:8080/messages
Content-Type: application/json

{
  "type": "SUCCESS",
  "data": "Hello World!"
}

### 에러 메시지 전송
POST localhost:8080/messages
Content-Type: application/json

{
  "type": "ERROR",
  "data": "Hello World!"
}
